version: '3.8'

services:
  postgres:
    image: postgres:18
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: osmaster
      POSTGRES_USER:
      POSTGRES_PASSWORD:

  wiremock:
    image: wiremock/wiremock:2.35.0
    container_name: wiremock
    ports:
      - '8081:8080'
    volumes:
      - ./wiremock:/home/wiremock
    command: ["--verbose", "--root-dir", "/home/wiremock"]

  localstack:
    image: localstack/localstack:3.4.0
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - ACTIVATE_PRO=false
    volumes:
      - "./localstack_data:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  postgres_data:
