spring.application.name=Service-OSMaster

# Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/osmaster
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true

# Swagger configuration
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# External api configuration
external.api.consultarCep.url=http://localhost:8081

#Aws S3 configuration
aws.s3.bucket-name=osmaster-bucket
aws.s3.localStack.url=http://localhost:4566
aws.s3.accessKey=
aws.s3.secretAccessKey=